#!/usr/bin/env bash

# Check if you have 'WIP' markers in code before commit to prevent debug code and info on remote git.
if git diff HEAD | grep -A1 "WIP" $1; then
    read -p "You're about to add a WIP commit, do you want to run the CI? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Nn]$' > /dev/null; then
        echo "[skip ci]" >> $1
    fi
fi
